/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { getCurrentUser } from "@/lib/auth/session";
import { votingIsOpen } from "@/lib/events/judging";
import { castVoteAction, changeVoteAction, withdrawVoteAction } from "@/app/competition/judging/actions";

export const dynamic = "force-dynamic";
export default async function VotePage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{ok?:string;error?:string}>}){
  const {id}=await params;const query=await searchParams;const user=await getCurrentUser();
  const event=await prisma.event.findUnique({where:{id},select:{id:true,title:true,description:true,active:true,public:true,resultMethod:true,votingOpenAt:true,votingCloseAt:true,resultsPublishedAt:true,allowVoteChange:true,voteCandidates:{where:{active:true,public:true},orderBy:[{sortOrder:"asc"},{createdAt:"asc"}],select:{id:true,ownerName:true,vehicleName:true,vehicleModel:true,imageUrl:true,description:true,startNumber:true}}}});
  if(!event||!event.active||!event.public||!["PUBLIC_VOTE_ONLY","JUDGE_AND_PUBLIC_VOTE"].includes(event.resultMethod))notFound();
  const ownVote=user?await prisma.publicVote.findUnique({where:{eventId_userId:{eventId:id,userId:user.id}},select:{candidateId:true}}):null;const open=votingIsOpen(event);
  return <main className="min-h-screen bg-black px-6 py-28 text-white"><div className="mx-auto max-w-7xl"><Link href={`/events/${id}`} className="text-sm text-zinc-400">← Tilbage til eventet</Link><p className="mt-8 text-sm uppercase tracking-[.4em] text-violet-300">Publikumsafstemning</p><h1 className="mt-4 text-5xl font-black">Stem på din favorit</h1><p className="mt-4 max-w-3xl text-zinc-400">{event.description}</p><p className="mt-6 rounded-2xl border border-white/10 p-4 font-bold">{event.resultsPublishedAt?"Resultater offentliggjort":open?"Afstemning åben":event.votingOpenAt?"Afstemning lukket":"Afstemning ikke åbnet"}</p>
  {query.ok?<p className="mt-4 rounded-2xl border border-emerald-400/30 bg-emerald-400/10 p-4 text-emerald-100">{query.ok}</p>:null}{query.error?<p className="mt-4 rounded-2xl border border-red-400/30 bg-red-400/10 p-4 text-red-100">{query.error}</p>:null}
  {event.voteCandidates.length===0?<div className="mt-8 rounded-[2rem] border border-white/10 p-8 text-center"><h2 className="text-2xl font-black">Ingen kandidater endnu</h2><p className="mt-2 text-zinc-400">Kandidaterne bliver vist her, når arrangøren har offentliggjort dem.</p></div>:<div className="mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{event.voteCandidates.map(candidate=>{const selected=ownVote?.candidateId===candidate.id;const hasOther=Boolean(ownVote&&!selected);return <article key={candidate.id} className={`overflow-hidden rounded-[2rem] border bg-white/[.04] ${selected?"border-violet-300":"border-white/10"}`}><div className="aspect-[4/3] bg-zinc-950"><img src={candidate.imageUrl} alt={`${candidate.vehicleName} · ${candidate.ownerName}`} className="h-full w-full object-cover"/></div><div className="p-6"><p className="text-xs font-black uppercase tracking-[.2em] text-zinc-500">{candidate.startNumber?`Startnummer ${candidate.startNumber}`:"Afstemningskandidat"}</p><h2 className="mt-2 text-3xl font-black">{candidate.vehicleName}</h2>{candidate.vehicleModel?<p className="mt-1 text-zinc-300">{candidate.vehicleModel}</p>:null}<p className="mt-3 font-bold text-violet-200">Ejer: {candidate.ownerName}</p>{candidate.description?<p className="mt-3 text-sm leading-6 text-zinc-400">{candidate.description}</p>:null}<div className="mt-5">{!user?<Link href={`/login?callbackUrl=/events/${id}/vote`} className="inline-flex rounded-full bg-white px-5 py-3 font-black text-black">Log ind for at stemme</Link>:selected?<div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-violet-300 px-5 py-3 font-black text-black">Din stemme</span><form action={withdrawVoteAction.bind(null,id)}><button disabled={!open} className="rounded-full border border-red-300/30 px-5 py-3 font-black text-red-200 disabled:opacity-40">Fortryd stemme</button></form></div>:hasOther?<form action={changeVoteAction.bind(null,id,candidate.id)} className="grid gap-3"><label className="text-xs text-zinc-400"><input name="confirm" type="checkbox" value="change"/> Bekræft skift til {candidate.vehicleName}</label><button disabled={!open||!event.allowVoteChange} className="w-fit rounded-full bg-white px-5 py-3 font-black text-black disabled:opacity-40">Skift stemme til denne bil</button></form>:<form action={castVoteAction.bind(null,id,candidate.id)}><button disabled={!open} className="rounded-full bg-white px-5 py-3 font-black text-black disabled:opacity-40">Stem på denne bil</button></form>}</div></div></article>})}</div>}
  <p className="mt-8 text-sm text-zinc-500">Stemmetal, point og foreløbige placeringer er skjult, indtil resultatet offentliggøres.</p></div></main>;
}
