"use client";

import { useState } from "react";
import ImageUploadField from "@/components/images/ImageUploadField";
import { deleteVoteCandidateAction, moveVoteCandidateAction, saveVoteCandidateAction, toggleVoteCandidateAction } from "@/app/competition/judging/candidate-actions";

type Option={id:string;label:string};
type Candidate={id:string;ownerName:string;vehicleName:string;vehicleModel:string|null;imageUrl:string;description:string|null;startNumber:string|null;participantId:string|null;vehicleId:string|null;ownerUserId:string|null;active:boolean;public:boolean;sortOrder:number};
const field="w-full rounded-xl border border-white/10 bg-black px-4 py-3 text-white";

export default function VoteCandidateManager({eventId,candidates,participants,vehicles,users,feedback}:{eventId:string;candidates:Candidate[];participants:Option[];vehicles:Option[];users:Option[];feedback?:{type:"ok"|"error";message:string}}){
  const [draftId]=useState(()=>crypto.randomUUID());
  return <section id="afstemningskandidater" className="mb-7 scroll-mt-8 rounded-[2rem] border border-white/10 bg-black p-6"><h3 className="text-2xl font-black">Afstemningskandidater</h3><p className="mt-2 text-sm text-zinc-400">Opret de biler, som registrerede brugere kan stemme på. Kandidater uden en Participant-kobling blokerer resultatpublicering.</p>
    {feedback?<p className={`mt-4 rounded-xl border p-3 text-sm font-bold ${feedback.type==="ok"?"border-emerald-400/30 bg-emerald-400/10 text-emerald-100":"border-red-400/30 bg-red-400/10 text-red-100"}`}>{feedback.message}</p>:null}
    <details className="mt-5 rounded-2xl border border-white/10 p-5"><summary className="cursor-pointer font-black">Opret kandidat</summary><CandidateForm eventId={eventId} candidateId={draftId} participants={participants} vehicles={vehicles} users={users}/></details>
    <div className="mt-5 grid gap-4">{candidates.map(candidate=><details key={candidate.id} className="rounded-2xl border border-white/10 p-5"><summary className="cursor-pointer"><span className="font-black">{candidate.vehicleName}</span><span className="ml-2 text-sm text-zinc-500">{candidate.ownerName} · {candidate.active&&candidate.public?"Synlig":"Skjult"}</span></summary><CandidateForm eventId={eventId} candidateId={candidate.id} candidate={candidate} participants={participants} vehicles={vehicles} users={users}/><div className="mt-4 flex flex-wrap gap-2"><form action={moveVoteCandidateAction.bind(null,eventId,candidate.id,"up")}><button className="rounded-full border border-white/15 px-4 py-2 text-sm font-bold">Flyt op</button></form><form action={moveVoteCandidateAction.bind(null,eventId,candidate.id,"down")}><button className="rounded-full border border-white/15 px-4 py-2 text-sm font-bold">Flyt ned</button></form><form action={toggleVoteCandidateAction.bind(null,eventId,candidate.id,!(candidate.active&&candidate.public))}><button className="rounded-full border border-white/15 px-4 py-2 text-sm font-bold">{candidate.active&&candidate.public?"Skjul":"Aktivér"}</button></form><form action={deleteVoteCandidateAction.bind(null,eventId,candidate.id)} className="flex items-center gap-2"><label className="text-xs text-zinc-400"><input name="confirm" type="checkbox" value="delete"/> Bekræft sletning</label><button className="rounded-full border border-red-400/30 px-4 py-2 text-sm font-bold text-red-200">Slet</button></form></div></details>)}</div>
  </section>;
}

function CandidateForm({eventId,candidateId,candidate,participants,vehicles,users}:{eventId:string;candidateId:string;candidate?:Candidate;participants:Option[];vehicles:Option[];users:Option[]}){
  return <form action={saveVoteCandidateAction.bind(null,eventId,candidateId)} className="mt-5 grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><ImageUploadField name="imageUrl" scope="vote" ownerId={`${eventId}-${candidateId}`} initialUrl={candidate?.imageUrl} label="Bilbillede" chooseLabel="Upload bilbillede" helpText="Kandidatens offentlige coverbillede." variant="cover"/></div><input name="vehicleName" required defaultValue={candidate?.vehicleName} placeholder="Bilens navn" className={field}/><input name="ownerName" required defaultValue={candidate?.ownerName} placeholder="Ejerens navn" className={field}/><input name="vehicleModel" defaultValue={candidate?.vehicleModel??""} placeholder="Model (valgfri)" className={field}/><input name="startNumber" defaultValue={candidate?.startNumber??""} placeholder="Startnummer" className={field}/><textarea name="description" defaultValue={candidate?.description??""} placeholder="Beskrivelse" className={`${field} md:col-span-2`}/><select name="participantId" defaultValue={candidate?.participantId??""} className={field}><option value="">Ingen Participant-kobling</option>{participants.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="vehicleId" defaultValue={candidate?.vehicleId??""} className={field}><option value="">Intet Vehicle-link</option>{vehicles.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="ownerUserId" defaultValue={candidate?.ownerUserId??""} className={field}><option value="">Ingen User-kobling</option>{users.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input name="sortOrder" type="number" defaultValue={candidate?.sortOrder??0} className={field}/><button className="w-fit rounded-full bg-white px-5 py-3 font-black text-black">{candidate?"Gem kandidat":"Opret kandidat"}</button></form>;
}
