-- CreateEnum
CREATE TYPE "ProfileStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'ARCHIVED');

-- AlterTable
ALTER TABLE "Event" ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "imageAlt" TEXT,
ADD COLUMN "public" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "thumbnailUrl" TEXT;

-- AlterTable
ALTER TABLE "User" ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "archivedAt" TIMESTAMP(3),
ADD COLUMN "deletedAt" TIMESTAMP(3),
ADD COLUMN "profileStatus" "ProfileStatus" NOT NULL DEFAULT 'ACTIVE';
