"use client";
/* eslint-disable @next/next/no-img-element */
import { useMemo, useRef, useState } from "react";
import { GALLERY_BATCH_LIMIT, GALLERY_UPLOAD_CONCURRENCY } from "@/lib/gallery/config";
import { validateImageFileMetadata } from "@/lib/images/image-upload";
import { runWithConcurrency } from "@/lib/gallery/batch";
import { createVideoBatchAction, saveAlbumAction } from "@/app/galleri/actions";

type Option = { id: string; title: string };
type QueueItem = { id: string; file: File; preview: string; status: "Klar" | "Uploader" | "Uploadet" | "Fejlet"; error?: string };
const field = "w-full rounded-2xl border border-white/10 bg-black px-4 py-3 text-white outline-none focus:border-white";

export default function GalleryAdmin({ albums, events, defaultAlbumId = "" }: { albums: Option[]; events: Option[]; defaultAlbumId?: string }) {
  const input = useRef<HTMLInputElement>(null); const [panel, setPanel] = useState<"album" | "images" | "videos" | null>(null); const [queue, setQueue] = useState<QueueItem[]>([]); const [albumId, setAlbumId] = useState(defaultAlbumId); const [eventId, setEventId] = useState(""); const [prefix, setPrefix] = useState(""); const [description, setDescription] = useState(""); const [running, setRunning] = useState(false);
  const uploaded = queue.filter((item) => item.status === "Uploadet").length; const failed = queue.filter((item) => item.status === "Fejlet").length;
  function addFiles(list: FileList | File[]) { const files = Array.from(list); const room = GALLERY_BATCH_LIMIT - queue.length; const added = files.slice(0, room).map((file) => { try { validateImageFileMetadata(file, "gallery"); return { id: crypto.randomUUID(), file, preview: URL.createObjectURL(file), status: "Klar" as const }; } catch (error) { return { id: crypto.randomUUID(), file, preview: "", status: "Fejlet" as const, error: error instanceof Error ? error.message : "Ugyldig fil." }; } }); setQueue((current) => [...current, ...added]); }
  async function upload(item: QueueItem) { setQueue((q) => q.map((x) => x.id === item.id ? { ...x, status: "Uploader", error: undefined } : x)); const body = new FormData(); body.set("file", item.file); body.set("albumId", albumId); body.set("eventId", eventId); body.set("titlePrefix", prefix); body.set("description", description); body.set("uploadKey", item.id); try { const response = await fetch("/api/gallery/images", { method: "POST", body }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error || "Upload fejlede."); setQueue((q) => q.map((x) => x.id === item.id ? { ...x, status: "Uploadet", error: undefined } : x)); } catch (error) { setQueue((q) => q.map((x) => x.id === item.id ? { ...x, status: "Fejlet", error: error instanceof Error ? error.message : "Upload fejlede." } : x)); } }
  async function run(items = queue.filter((item) => item.status === "Klar")) { if (!items.length) return; setRunning(true); await runWithConcurrency(items, GALLERY_UPLOAD_CONCURRENCY, upload); setRunning(false); }
  const summary = useMemo(() => `${uploaded} af ${queue.length} billeder uploadet${failed ? ` · ${failed} fejlede` : ""}`, [uploaded, failed, queue.length]);
  return <section id="media-admin" className="mt-10 rounded-[2rem] border border-white/10 bg-white/[0.04] p-5">
    <p className="mb-4 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-3 text-sm font-bold text-emerald-100">Gyldige billeder bliver offentliggjort med det samme.</p>
    <div className="flex flex-wrap gap-3"><button onClick={() => setPanel("album")} className="rounded-full bg-white px-5 py-3 font-black text-black">Opret album</button><button onClick={() => setPanel("images")} className="rounded-full border border-white/15 px-5 py-3 font-black">Upload billeder</button><button onClick={() => setPanel("videos")} className="rounded-full border border-white/15 px-5 py-3 font-black">Tilføj videoer</button></div>
    {panel === "album" ? <form action={saveAlbumAction} className="mt-6 grid gap-4 md:grid-cols-2"><input name="title" required placeholder="Albumnavn" className={field}/><select name="eventId" className={field}><option value="">Intet event</option>{events.map((e)=><option key={e.id} value={e.id}>{e.title}</option>)}</select><textarea name="description" placeholder="Beskrivelse (valgfri)" className={`${field} md:col-span-2`}/><input name="sortOrder" type="number" defaultValue="0" className={field}/><p className="text-sm text-zinc-400 md:col-span-2">Albummet oprettes aktivt og offentligt. Det kan skjules bagefter.</p><button className="rounded-full bg-white px-5 py-3 font-black text-black">Opret album</button></form> : null}
    {panel === "images" ? <div className="mt-6"><div className="grid gap-4 md:grid-cols-2"><select value={albumId} onChange={(e)=>setAlbumId(e.target.value)} className={field}><option value="">Uden album</option>{albums.map((a)=><option key={a.id} value={a.id}>{a.title}</option>)}</select><select value={eventId} onChange={(e)=>setEventId(e.target.value)} className={field}><option value="">Intet event</option>{events.map((e)=><option key={e.id} value={e.id}>{e.title}</option>)}</select><input value={prefix} onChange={(e)=>setPrefix(e.target.value)} placeholder="Fælles titelprefix (valgfrit)" className={field}/><input value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="Fælles beskrivelse (valgfri)" className={field}/></div><div onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{e.preventDefault(); addFiles(e.dataTransfer.files);}} className="mt-4 rounded-2xl border border-dashed border-white/20 p-8 text-center"><p className="font-black">Træk op til {GALLERY_BATCH_LIMIT} JPG-, PNG- eller WebP-filer hertil</p><p className="mt-2 text-sm text-zinc-500">Maks. 8 MB pr. billede · højst {GALLERY_UPLOAD_CONCURRENCY} samtidige uploads</p><button type="button" onClick={()=>input.current?.click()} className="mt-4 rounded-full bg-white px-5 py-2.5 font-black text-black">Vælg flere filer</button><input ref={input} multiple type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(e)=>e.target.files&&addFiles(e.target.files)}/></div><div className="mt-5 grid gap-3">{queue.map((item)=><div key={item.id} className="flex min-w-0 items-center gap-4 rounded-2xl border border-white/10 p-3">{item.preview?<img src={item.preview} alt="" className="h-16 w-20 rounded-xl object-cover"/>:<div className="h-16 w-20 rounded-xl bg-red-500/10"/>}<div className="min-w-0 flex-1"><p className="truncate font-bold">{item.file.name}</p><p className="text-xs text-zinc-500">{(item.file.size/1024/1024).toFixed(2)} MB · {item.status}</p>{item.error?<p className="text-sm text-red-300">{item.error}</p>:null}</div>{item.status === "Fejlet" && !running ? <button onClick={()=>void run([{...item,status:"Klar"}])} className="text-sm font-black">Prøv igen</button>:null}{item.status === "Klar"&&!running?<button onClick={()=>setQueue((q)=>q.filter((x)=>x.id!==item.id))} className="text-sm text-zinc-400">Fjern</button>:null}</div>)}</div>{queue.length?<div className="mt-5 flex flex-wrap items-center gap-4"><button disabled={running} onClick={()=>void run()} className="rounded-full bg-white px-5 py-3 font-black text-black disabled:opacity-50">{running?"Uploader…":"Start samlet upload"}</button>{failed&&!running?<button onClick={()=>void run(queue.filter((x)=>x.status==="Fejlet").map((x)=>({...x,status:"Klar"})))} className="rounded-full border border-white/15 px-5 py-3 font-black">Prøv fejlede igen</button>:null}<p aria-live="polite" className="text-sm text-zinc-400">{summary}</p></div>:null}</div> : null}
    {panel === "videos" ? <form action={createVideoBatchAction} className="mt-6 grid gap-4 md:grid-cols-2"><select name="albumId" defaultValue={defaultAlbumId} className={field}><option value="">Uden album</option>{albums.map((a)=><option key={a.id} value={a.id}>{a.title}</option>)}</select><select name="eventId" className={field}><option value="">Intet event</option>{events.map((e)=><option key={e.id} value={e.id}>{e.title}</option>)}</select><textarea name="videos" required rows={7} placeholder={"Én URL pr. linje\neller: Titel | URL"} className={`${field} md:col-span-2`}/><textarea name="description" placeholder="Fælles beskrivelse (valgfri)" className={`${field} md:col-span-2`}/><p className="text-sm text-zinc-500 md:col-span-2">Alle links valideres samlet. Ved ugyldige linjer gemmes ingen, og linjenumrene vises.</p><button className="rounded-full bg-white px-5 py-3 font-black text-black">Tilføj videoer</button></form> : null}
  </section>;
}
