"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useState } from "react";

type ImageItem = { id: string; imageUrl: string; title: string; description: string | null; photographer: string | null };
export default function GalleryLightbox({ images }: { images: ImageItem[] }) {
  const [index, setIndex] = useState<number | null>(null);
  useEffect(() => { if (index === null) return; const key = (event: KeyboardEvent) => { if (event.key === "Escape") setIndex(null); if (event.key === "ArrowRight") setIndex((index + 1) % images.length); if (event.key === "ArrowLeft") setIndex((index - 1 + images.length) % images.length); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [index, images.length]);
  return <><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">{images.map((item, i)=><button key={item.id} onClick={()=>setIndex(i)} className="group overflow-hidden rounded-2xl border border-white/10 bg-white/[0.04] text-left"><img src={item.imageUrl} alt={item.title} className="aspect-[4/3] h-full max-h-80 w-full object-cover transition group-hover:scale-105"/><div className="p-4"><p className="font-black">{item.title}</p>{item.photographer?<p className="mt-1 text-xs text-zinc-500">Foto: {item.photographer}</p>:null}</div></button>)}</div>{index!==null&&images[index]?<div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-black/95 p-4" onClick={()=>setIndex(null)}><button aria-label="Luk" className="absolute right-5 top-5 text-3xl">×</button><button aria-label="Forrige" onClick={(e)=>{e.stopPropagation();setIndex((index-1+images.length)%images.length)}} className="absolute left-3 text-4xl">‹</button><div onClick={(e)=>e.stopPropagation()} className="max-h-[92vh] max-w-6xl"><img src={images[index].imageUrl} alt={images[index].title} className="max-h-[78vh] w-full object-contain"/><div className="mt-3 text-center"><h2 className="text-xl font-black">{images[index].title}</h2>{images[index].description?<p className="mt-1 text-zinc-400">{images[index].description}</p>:null}{images[index].photographer?<p className="mt-1 text-sm text-zinc-500">Foto: {images[index].photographer}</p>:null}</div></div><button aria-label="Næste" onClick={(e)=>{e.stopPropagation();setIndex((index+1)%images.length)}} className="absolute right-3 text-4xl">›</button></div>:null}</>;
}
