/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { notFound } from "next/navigation";
import Footer from "@/components/layout/Footer";
import GalleryAdmin from "@/components/gallery/GalleryAdmin";
import GalleryLightbox from "@/components/gallery/GalleryLightbox";
import ImageUploadField from "@/components/images/ImageUploadField";
import { getCurrentUser } from "@/lib/auth/session";
import { GALLERY_PAGE_SIZE, galleryPage, galleryPageOffset, isGalleryManager } from "@/lib/gallery/config";
import { externalVideoEmbedUrl } from "@/lib/gallery/media";
import { prisma } from "@/lib/prisma";
import { bulkGalleryAction, deleteAlbumAction, moveAlbumAction, saveAlbumAction, saveGalleryItemAction, setAlbumCoverAction } from "../actions";

export const dynamic = "force-dynamic"; const field="w-full rounded-2xl border border-white/10 bg-black px-4 py-3 text-white";
export default async function AlbumPage({ params, searchParams }: { params: Promise<{albumId:string}>; searchParams: Promise<{ok?:string;error?:string;page?:string}> }) {
  const [{albumId}, query, actor, albums, events] = await Promise.all([params, searchParams, getCurrentUser(), prisma.galleryAlbum.findMany({orderBy:{sortOrder:"asc"},select:{id:true,title:true}}), prisma.event.findMany({orderBy:{startsAt:"desc"},select:{id:true,title:true}})]); const canManage=Boolean(actor&&isGalleryManager(actor.role)); const unassigned=albumId==="uden-album";
  const album=unassigned?null:await prisma.galleryAlbum.findUnique({where:{id:albumId},include:{event:{select:{id:true,title:true,slug:true}}}}); if(!unassigned&&(!album||(!canManage&&(!album.active||!album.public)))) notFound();
  const page=galleryPage(query.page); const mediaWhere={albumId:unassigned?null:albumId,...(!canManage?{active:true,public:true}:{})};
  const [items,total,countGroups,firstImage]=await Promise.all([
    prisma.galleryImage.findMany({where:mediaWhere,orderBy:[{sortOrder:"asc"},{createdAt:"desc"}],skip:galleryPageOffset(page),take:GALLERY_PAGE_SIZE}),
    prisma.galleryImage.count({where:mediaWhere}),
    prisma.galleryImage.groupBy({by:["mediaType"],where:mediaWhere,_count:{_all:true}}),
    prisma.galleryImage.findFirst({where:{...mediaWhere,mediaType:"IMAGE",imageUrl:{not:null}},orderBy:[{sortOrder:"asc"},{createdAt:"desc"}],select:{imageUrl:true}}),
  ]);
  const totalImages=countGroups.find((row)=>row.mediaType==="IMAGE")?._count._all??0; const totalVideos=countGroups.find((row)=>row.mediaType==="VIDEO")?._count._all??0; const totalPages=Math.max(1,Math.ceil(total/GALLERY_PAGE_SIZE));
  const images=items.filter(i=>i.mediaType==="IMAGE"&&i.imageUrl).map(i=>({...i,imageUrl:i.imageUrl!})); const videos=items.filter(i=>i.mediaType==="VIDEO"&&i.videoUrl); const cover=album?.coverImageUrl||firstImage?.imageUrl;
  return <main className="min-h-screen bg-black text-white"><section className="px-5 pb-24 pt-28"><div className="mx-auto max-w-7xl"><Link href="/galleri" className="text-sm font-black text-zinc-400">← Alle albums</Link>{query.ok?<p className="mt-5 rounded-2xl bg-emerald-500/10 p-4 text-emerald-200">{query.ok}</p>:null}{query.error?<p className="mt-5 rounded-2xl bg-red-500/10 p-4 text-red-200">{query.error}</p>:null}<div className="mt-8 grid gap-8 lg:grid-cols-[1.4fr_1fr] lg:items-end"><div className="aspect-[16/8] overflow-hidden rounded-[2rem] bg-zinc-950">{cover?<img src={cover} alt="" className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-3xl font-black text-zinc-700">DarkLight</div>}</div><div><p className="text-sm font-black uppercase tracking-[.3em] text-zinc-500">Album</p><h1 className="mt-3 text-4xl font-black md:text-6xl">{album?.title||"Uden album"}</h1>{album?.description?<p className="mt-5 leading-7 text-zinc-400">{album.description}</p>:null}{album?.event?<Link href={`/events/${album.event.slug}`} className="mt-4 inline-block font-black underline">{album.event.title}</Link>:null}<p className="mt-5 text-sm text-zinc-500">{totalImages} billeder · {totalVideos} videoer · {total} medier</p></div></div>
  {canManage?<><GalleryAdmin albums={albums} events={events} defaultAlbumId={unassigned?"":albumId}/>{album?<details className="mt-6 rounded-[2rem] border border-white/10 p-5"><summary className="cursor-pointer text-xl font-black">Redigér album</summary><form action={saveAlbumAction} className="mt-5 grid gap-4 md:grid-cols-2"><input type="hidden" name="id" value={album.id}/><input name="title" defaultValue={album.title} className={field}/><select name="eventId" defaultValue={album.eventId||""} className={field}><option value="">Intet event</option>{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select><textarea name="description" defaultValue={album.description||""} className={`${field} md:col-span-2`}/><div className="md:col-span-2"><ImageUploadField name="coverImageUrl" scope="gallery" ownerId={album.id} initialUrl={album.coverImageUrl||""} label="Separat albumcover" chooseLabel="Upload cover" helpText="Manuelt cover har prioritet; ellers bruges første aktive billede."/></div><input name="sortOrder" type="number" defaultValue={album.sortOrder} className={field}/><label><input name="active" type="checkbox" defaultChecked={album.active}/> Aktiv</label><label><input name="public" type="checkbox" defaultChecked={album.public}/> Offentlig</label><button className="rounded-full bg-white px-5 py-3 font-black text-black">Gem album</button></form><div className="mt-5 flex gap-3"><form action={moveAlbumAction.bind(null,album.id,"up")}><button className="rounded-full border border-white/15 px-4 py-2 font-black">Flyt op</button></form><form action={moveAlbumAction.bind(null,album.id,"down")}><button className="rounded-full border border-white/15 px-4 py-2 font-black">Flyt ned</button></form></div><form action={deleteAlbumAction.bind(null,album.id)} className="mt-6 rounded-2xl border border-red-400/20 p-4"><p className="font-black text-red-200">Slet album</p><select name="mode" defaultValue="detach" className={`${field} mt-3`}><option value="detach">Flyt medier til Uden album (anbefalet)</option><option value="permanent">Slet album og alle medier permanent</option></select><input name="confirmation" placeholder="Ved permanent sletning: SLET PERMANENT" className={`${field} mt-3`}/><button className="mt-3 font-black text-red-300">Bekræft sletning</button></form></details>:null}</>:null}
  <section className="mt-14"><h2 className="text-3xl font-black">Billeder</h2>{canManage&&items.length?<form action={bulkGalleryAction} className="mt-5"><input type="hidden" name="currentAlbumId" value={unassigned?"":albumId}/><div className="flex flex-wrap gap-3 rounded-2xl border border-white/10 p-4"><select name="bulkAction" className={field}><option value="move">Flyt valgte</option><option value="hide">Skjul valgte</option><option value="activate">Aktivér valgte</option><option value="delete">Slet valgte</option></select><select name="targetAlbumId" className={field}><option value="">Uden album</option>{albums.filter(a=>a.id!==albumId).map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select><input name="confirmation" placeholder="Ved sletning: SLET" className={field}/><button className="rounded-full bg-white px-5 py-3 font-black text-black">Udfør på valgte</button></div><div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">{items.map(item=><div key={item.id} className="overflow-hidden rounded-2xl border border-white/10 bg-white/[.04]"><label className="block cursor-pointer"><div className="relative"><input name="itemId" value={item.id} type="checkbox" className="absolute left-3 top-3 z-10 h-5 w-5"/>{(item.imageUrl||item.thumbnailUrl)?<img src={(item.imageUrl||item.thumbnailUrl)!} alt="" className="aspect-[4/3] w-full object-cover"/>:<div className="flex aspect-[4/3] items-center justify-center">▶</div>}</div></label><div className="p-4"><p className="font-black">{item.title}</p><p className="text-xs text-zinc-500">{item.mediaType}{!item.active||!item.public?" · Skjult":""}</p>{album&&item.mediaType==="IMAGE"&&item.imageUrl?<button formAction={setAlbumCoverAction.bind(null,album.id,item.id)} className="mt-2 text-xs font-black underline">Brug som cover</button>:null}<details className="mt-3"><summary className="cursor-pointer text-xs font-black">Redigér</summary><div className="mt-3 grid gap-2"><input name="noop" className="hidden"/><button formAction={undefined} type="button" className="text-left text-xs text-zinc-500">Åbn separat redigering nedenfor</button></div></details></div></div>)}</div></form>:images.length?<GalleryLightbox images={images}/>:<p className="mt-5 text-zinc-500">Ingen billeder.</p>}</section>
  {canManage&&items.length?<section className="mt-10"><h2 className="text-2xl font-black">Redigér mediedetaljer</h2><div className="mt-4 grid gap-3">{items.map(item=><details key={item.id} className="rounded-2xl border border-white/10 p-4"><summary className="cursor-pointer font-black">{item.title}</summary><form action={saveGalleryItemAction} className="mt-4 grid gap-3 md:grid-cols-2"><input type="hidden" name="id" value={item.id}/><input type="hidden" name="mediaType" value={item.mediaType}/><input type="hidden" name="imageUrl" value={item.imageUrl||""}/><input type="hidden" name="videoUrl" value={item.videoUrl||""}/><input type="hidden" name="thumbnailUrl" value={item.thumbnailUrl||""}/><input name="title" defaultValue={item.title} className={field}/><input name="photographer" defaultValue={item.photographer||""} placeholder="Fotograf" className={field}/><textarea name="description" defaultValue={item.description||""} className={`${field} md:col-span-2`}/><select name="albumId" defaultValue={item.albumId||""} className={field}><option value="">Uden album</option>{albums.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select><select name="eventId" defaultValue={item.eventId||""} className={field}><option value="">Intet event</option>{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select><input name="sortOrder" type="number" defaultValue={item.sortOrder} className={field}/><label><input name="active" type="checkbox" defaultChecked={item.active}/> Aktiv</label><label><input name="public" type="checkbox" defaultChecked={item.public}/> Offentlig</label><button className="rounded-full bg-white px-5 py-3 font-black text-black">Gem medie</button></form></details>)}</div></section>:null}
  {videos.length?<section className="mt-14"><h2 className="text-3xl font-black">Videoer</h2><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{videos.map(video=>{const embed=externalVideoEmbedUrl(video.videoUrl!);return <article key={video.id} className="overflow-hidden rounded-2xl border border-white/10 bg-white/[.04]">{embed?<iframe src={embed} title={video.title} loading="lazy" allow="fullscreen; picture-in-picture" className="aspect-video w-full"/>:video.thumbnailUrl?<img loading="lazy" src={video.thumbnailUrl} alt="" className="aspect-video w-full object-cover"/>:<div className="flex aspect-video items-center justify-center text-5xl">▶</div>}<div className="p-5"><h3 className="text-xl font-black">{video.title}</h3>{video.description?<p className="mt-2 text-sm text-zinc-400">{video.description}</p>:null}<a href={video.videoUrl!} target="_blank" rel="noopener noreferrer" className="mt-4 inline-block font-black underline">Åbn video</a></div></article>})}</div></section>:null}
  {totalPages>1?<nav aria-label="Galleri-sider" className="mt-12 flex flex-wrap items-center justify-center gap-3">{page>1?<Link href={`?page=${page-1}`} className="rounded-full border border-white/15 px-5 py-3 font-black">Forrige</Link>:null}<span className="text-sm text-zinc-500">Side {page} af {totalPages}</span>{page<totalPages?<Link href={`?page=${page+1}`} className="rounded-full bg-white px-5 py-3 font-black text-black">Indlæs næste 24</Link>:null}</nav>:null}</div></section><Footer/></main>;
}
