ALTER TABLE "Event"
ADD COLUMN "usesParticipantRegistration" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "usesVehicles" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "requiresVehicleApproval" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "usesHeats" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "usesBracket" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "usesResults" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "usesPrizes" BOOLEAN NOT NULL DEFAULT true;
