import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { GALLERY_BATCH_LIMIT, GALLERY_UPLOAD_CONCURRENCY, isGalleryManager } from "./config";
import { parseVideoBatch, resolveAlbumCover, runWithConcurrency, validateGalleryBatch } from "./batch";
import { externalVideoEmbedUrl } from "./media";

test("gallery RBAC permits only the three manager roles", () => { assert.equal(isGalleryManager("SUPER_ADMIN"), true); assert.equal(isGalleryManager("ADMIN"), true); assert.equal(isGalleryManager("EVENT_MANAGER"), true); assert.equal(isGalleryManager("USER"), false); });
test("gallery batch enforces 20 files and validates each file independently", () => { const files = Array.from({length:25},(_,i)=>({name:`${i}.jpg`,type:"image/jpeg",size:i===4?9*1024*1024:100})); const result=validateGalleryBatch(files); assert.equal(result.length,GALLERY_BATCH_LIMIT); assert.match(result[4].error!,/8 MB/); assert.equal(result[5].error,null); assert.match(validateGalleryBatch([{name:"x.gif",type:"image/gif",size:10}])[0].error!,/JPG/); });
test("concurrency is bounded and one rejection can be handled by the worker without stopping peers", async()=>{let active=0,max=0,finished=0; await runWithConcurrency([1,2,3,4,5,6],GALLERY_UPLOAD_CONCURRENCY,async(i)=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,5));active--;if(i!==2)finished++;});assert.equal(max,3);assert.equal(finished,5);});
test("video batch reports individual invalid lines and accepts supported providers",()=>{const rows=parseVideoBatch("YouTube | https://youtube.com/watch?v=abc\nhttps://vimeo.com/123\nhttps://example.com/x\nhttps://twitch.tv/darklight\nhttps://streamable.com/xyz");assert.equal(rows.length,5);assert.equal(rows[2].url,null);assert.ok(rows.filter(r=>r.url).length===4);assert.match(externalVideoEmbedUrl(rows[0].url!)!,/youtube-nocookie/);});
test("cover priority is manual, then first active image, then placeholder",()=>{const images=[{imageUrl:"/hidden.jpg",active:false},{imageUrl:"/first.jpg",active:true}];assert.equal(resolveAlbumCover("/manual.jpg",images),"/manual.jpg");assert.equal(resolveAlbumCover(null,images),"/first.jpg");assert.equal(resolveAlbumCover(null,[]),"/darklight-placeholder.svg");});
test("migration preserves legacy album text and existing rows as albumId null",()=>{const sql=readFileSync("prisma/migrations/20260806120000_add_gallery_albums/migration.sql","utf8");const schema=readFileSync("prisma/schema.prisma","utf8");assert.match(schema,/album\s+String\?/);assert.match(schema,/albumId\s+String\?/);assert.doesNotMatch(sql,/UPDATE\s+"GalleryImage"/i);});
test("album deletion defaults to detach and permanent mode requires phrase",()=>{const source=readFileSync("app/galleri/actions.ts","utf8");const helper=readFileSync("lib/gallery/album-deletion.ts","utf8");assert.match(source,/updateMany[\s\S]*albumId: null/);assert.match(helper,/SLET PERMANENT/);assert.match(source,/galleryImage\.deleteMany/);});
test("cleanup only sends owned Blob URLs and deduplicates bulk URLs",()=>{const source=readFileSync("lib/gallery/album-deletion.ts","utf8");assert.match(source,/new Set/);assert.match(source,/isOwnedBlobImage/);const cleanup=readFileSync("lib/images/blob-cleanup.ts","utf8");assert.match(cleanup,/if \(!url \|\| !isOwnedBlobImage\(url\)\) return false/);});
test("upload route uses idempotency, stable locked ordering, unique album path and cleanup",()=>{const source=readFileSync("app/api/gallery/images/route.ts","utf8");assert.match(source,/findUnique\(\{ where: \{ uploadKey: payload\.uploadKey \} \}\)/);assert.match(source,/pg_advisory_xact_lock/);assert.match(source,/albumId \|\| "unassigned"/);assert.match(source,/deleteNewBlobAfterFailedSave\(blobUrl, null\)/);});
test("public queries filter albums and media by active and public",()=>{const overview=readFileSync("app/galleri/page.tsx","utf8");const detail=readFileSync("app/galleri/[albumId]/page.tsx","utf8");assert.match(overview,/active: true, public: true/);assert.match(detail,/active:true,public:true/);});
